# action.yml
name: "Upload config data"
description: "Upload config data to Devops Config"
inputs:
  instance-url:
    description: "ServiceNow Instance"
    required: true
  devops-integration-user-name:
    description: "ServiceNow Username"
    reqired: true
  devops-integration-user-password:
    description: "ServiceNow Password"
    required: true
  application:
    description: "Devops Config Application"
    required: true
  target:
    description: "Devops Config object against which to upload (component|collection|deployable)"
    required: true
  target-name:
    description: "Name of the collection or deployable against which to upload"
    required: false
  filename:
    description: "Name of the file to upload"
    required: true
  data-format:
    description: "Format of the file to upload"
    required: true
  auto-validate:
    description: "Validate config data after upload (true|false)"
    required: true
    default: true
  publish-option:
    description: "Publish after successfull validation"
    required: true
    default: "publish_valid"
  auto-delete:
    description: "Delete content that is not part of the upload payload"
    required: false
    default: false
  name-path:
    description: "Path to upload against in the data model"
    required: false
  changeset:
    description: "Devops Config Changeset number"
    required: false
outputs:
  changeset:
    description: "Devops Config Changeset"
  validation:
    description: "Validation status"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.instance-url }}
    - ${{ inputs.devops-integration-user-name }}
    - ${{ inputs.devops-integration-user-password }}
    - ${{ inputs.application }}
    - ${{ inputs.target }}
    - ${{ inputs.target-name }}
    - ${{ inputs.filename }}
    - ${{ inputs.data-format }}
    - ${{ inputs.auto-validate }}
    - ${{ inputs.publish-option }}
    - ${{ inputs.name-path }}
    - ${{ inputs.changeset }}
    - ${{ inputs.auto-delete }}
